# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i3fOFMxWeG7_plPrFIXHhS0ah7jfuPVf
"""

!pip install scikit-learn

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# ----------------------------
# Predefined FAQ Dataset
# ----------------------------
faq_data = {
    "What is your name?": "I am an FAQ chatbot built using NLP techniques.",
    "How do I reset my password?": "Go to settings > account > reset password, and follow the instructions sent to your email.",
    "What are your working hours?": "We are available 24/7 to assist you online.",
    "How can I contact support?": "You can reach our support team via email at support@example.com.",
    "Do you offer refunds?": "Yes, refunds are available within 30 days of purchase.",
    "How do I track my order?": "You can track your order using the tracking link sent to your email after purchase.",
    "Is my payment information secure?": "Yes, we use industry-standard encryption to protect your payment data.",
    "Can I change my delivery address?": "Yes, you can update your delivery address before the order is shipped.",
}

questions = list(faq_data.keys())
answers = list(faq_data.values())

# ----------------------------
# TF-IDF Vectorization
# ----------------------------
vectorizer = TfidfVectorizer(stop_words="english")
question_vectors = vectorizer.fit_transform(questions)

# Bonus: fallback threshold — below this, we don't trust the match
CONFIDENCE_THRESHOLD = 0.3

def get_response(user_query):
    user_vector = vectorizer.transform([user_query])
    similarity_scores = cosine_similarity(user_vector, question_vectors)
    best_match_index = similarity_scores.argmax()
    confidence = similarity_scores[0][best_match_index]

    if confidence < CONFIDENCE_THRESHOLD:
        return "Sorry, I couldn't find a relevant answer. Please rephrase your question or contact support.", confidence

    return answers[best_match_index], confidence

# ----------------------------
# Chat Loop
# ----------------------------
print("FAQ Chatbot (type 'exit' to stop)\n")

while True:
    user_query = input("You: ").strip()
    if user_query.lower() == "exit":
        print("Chatbot: Goodbye!")
        break
    if user_query == "":
        print("Chatbot: Please type a question.\n")
        continue

    response, confidence = get_response(user_query)
    print(f"Chatbot: {response}")
    print(f"(Confidence Score: {confidence:.2f})\n")